name: jpnurmi
description: Personal website.
publish_to: 'none'

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  material_design_icons_flutter: ^6.0.0
  simple_animations: ^5.0.0
  supercharged: ^2.1.1
  url_launcher: ^6.1.4

flutter:
  uses-material-design: true
  assets:
    - icons/canonical.png
    - icons/dart.png
    - icons/flutter.png
    - icons/ubuntu.png
    - images/profile.png
